[package]
name = "influxdb3_server"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
async-trait = "0.1"
authz = { path = "../authz", features = ["http"] }
futures = "0.3.28"
hyper = "0.14"
influxdb-line-protocol = { path = "../influxdb_line_protocol" }
observability_deps = { path = "../observability_deps" }
metric = { path = "../metric" }
metric_exporters = { path = "../metric_exporters" }
thiserror = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
tokio-util = { version = "0.7.9" }
tonic = { workspace = true }
trace = { path = "../trace/" }
trace_exporters = { path = "../trace_exporters" }
trace_http = { path = "../trace_http" }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
serde_urlencoded = "0.7.0"
tower = "0.4.13"
